# Generated by Django 3.2.5 on 2021-07-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('receipt_number', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
