# Generated by Django 3.2.7 on 2021-10-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=100)),
                ('maize_bran', models.IntegerField(default=0)),
                ('cotton', models.IntegerField(default=0)),
                ('sun_flower', models.IntegerField(default=0)),
                ('salt', models.IntegerField(default=0)),
                ('layers_premix', models.IntegerField(default=0)),
                ('shells', models.IntegerField(default=0)),
                ('maize_boaster', models.IntegerField(default=0)),
                ('egg_boaster', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('receipt_number', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('amount', models.IntegerField(default=0)),
                ('transport', models.IntegerField()),
                ('onloading', models.IntegerField()),
                ('offloading', models.IntegerField()),
                ('grinding', models.IntegerField()),
                ('cost_of_supply', models.IntegerField(default=0)),
                ('pricing', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialQuantities',
            fields=[
                ('quantity_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('maize_bran', models.IntegerField(default=0)),
                ('cotton', models.IntegerField(default=0)),
                ('sun_flower', models.IntegerField(default=0)),
                ('fish', models.IntegerField(default=0)),
                ('salt', models.IntegerField(default=0)),
                ('general_purpose_premix', models.IntegerField(default=0)),
                ('layers_premix', models.IntegerField(default=0)),
                ('shells', models.IntegerField(default=0)),
                ('meat_boaster', models.IntegerField(default=0)),
                ('egg_boaster', models.IntegerField(default=0)),
            ],
        ),
    ]
