# Generated by Django 3.2.7 on 2021-10-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profit_pen_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='pricing',
        ),
    ]
