# Generated by Django 3.2.5 on 2021-07-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_pen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='fullamount',
            field=models.IntegerField(null=True),
        ),
    ]
