# Generated by Django 3.2.5 on 2021-08-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_pen_app', '0002_auto_20210730_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='fullamount',
            new_name='cost_of_supply',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='pricing',
            field=models.IntegerField(null=True),
        ),
    ]
