# Generated by Django 3.2.7 on 2021-11-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profit_pen_app', '0003_auto_20211104_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='maize_boaster',
            new_name='meat_boaster',
        ),
    ]
