# Generated by Django 3.2.7 on 2021-11-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_pen_app', '0004_rename_maize_boaster_product_meat_boaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuantities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('broilers_mash', models.IntegerField(default=0)),
                ('chick_mash', models.IntegerField(default=0)),
                ('egg_boaster', models.IntegerField(default=0)),
                ('growers_mash', models.IntegerField(default=0)),
                ('layers_mash', models.IntegerField(default=0)),
                ('meat_boaster', models.IntegerField(default=0)),
            ],
        ),
    ]
