# Generated by Django 3.2.5 on 2021-08-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_pen_app', '0004_auto_20210803_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=100)),
                ('maize_bran', models.IntegerField(default=0)),
                ('cotton', models.IntegerField(default=0)),
                ('sun_flower', models.IntegerField(default=0)),
                ('salt', models.IntegerField(default=0)),
                ('layers_premix', models.IntegerField(default=0)),
                ('shells', models.IntegerField(default=0)),
                ('maize_boaster', models.IntegerField(default=0)),
                ('egg_boaster', models.IntegerField(default=0)),
            ],
        ),
    ]
