# Generated by Django 3.2.7 on 2021-11-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profit_pen_app', '0005_productquantities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productquantities',
            old_name='egg_boaster',
            new_name='old_pig',
        ),
        migrations.RenameField(
            model_name='productquantities',
            old_name='meat_boaster',
            new_name='young_pig',
        ),
    ]
