# Generated by Django 3.2.7 on 2021-11-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profit_pen_app', '0006_auto_20211106_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productquantities',
            old_name='broilers_mash',
            new_name='broilers_marsh',
        ),
        migrations.RenameField(
            model_name='productquantities',
            old_name='chick_mash',
            new_name='chick_marsh',
        ),
        migrations.RenameField(
            model_name='productquantities',
            old_name='growers_mash',
            new_name='growers_marsh',
        ),
        migrations.RenameField(
            model_name='productquantities',
            old_name='layers_mash',
            new_name='layers_marsh',
        ),
    ]
